# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8b904bf8667a3d98831e526a8c7a0253822ac85e40a9427ef85aaafe03f0996c17fe324f955b9b02a47b6cce1a911841faafce54c0eacb541674971d5698c821

test:
  secret_key_base: e5cdaab163c17a72f9fc09e9adb67d705a10fda58954107b424ea283fa8671ad686bd8a7241f93aecf43b2b8387625cd0b2facd6707086ecb347e9007a9a3576

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
